### ISSUE TITLE
Configuring imageModels now required?

### ISSUE THREAD

**Issue by zefhemel** [justyns/silverbullet-ai#21]
It seems that in the version things break (at least chat) unless I configure `imageModels`. This is what I have in my SETTINGS right now:

```
ai:
  imageModels:
  - name: dall-e-3
    modelName: dall-e-3
    provider: dalle
  - name: dall-e-2
    modelName: dall-e-2
    provider: dalle
  textModels:
  - name: gpt-4-turbo
    provider: openai
    modelName: gpt-4-0125-preview
```

If I remove the `imageModels` section I get a imageModels related error whenever I execute a command.
