### ISSUE TITLE
Suggest name command

### ISSUE THREAD

**Issue by zefhemel** [justyns/silverbullet-ai#28]
I often use Quick Note to quickly jot something down. Afterwards it's hard to find and I cannot always be bothered to come up with a proper page name. I think AI can help here. ChatGPT always comes up with reasonable names for chats and I think this plug could do the same. 

What I'm suggesting is a "AI: Suggest Page Name" (or similar) command that based on the page content suggests perhaps 3 possible names (in a filtered list for instance) and if the user selects one, renames the page. 

I can imagine that in practice you'd want to guide AI a bit in your naming schemes so perhaps a type of preprompt text setting may be useful as well.

**Comment by zefhemel** [comment]
The more I think about it, the more I believe a way to instruct it will be vital. For instance I may want to say something along the lines of "if this page contains a #blog tag, make sure the page title is prefixed with Blog/"

**Comment by justyns** [comment]
@zefhemel Thanks for the suggestion!   I have a few helper spacescript commands like 'Move to Receipts' that this could potentially replace.  It's available in the main branch now if you want to give it a try.   By default, it'll use this prompt:

```
You are an AI note-naming assistant. Your task is to suggest three to five possible names for the provided note content. Please adhere to the following guidelines:
- Provide each name on a new line.
- Avoid most special characters or symbols. Spaces are acceptable. Forward slashes are allowed as folder seperators. Hyphens are allowed.
- Ensure the names are concise and relevant to the content.
- Avoid suggesting the same name as the current note.
- Include as much detail as possible within 3 to 10 words.
- Do not change the folder or prefix of the note name unless explicitly requested by the user.
- Include the current folder name (with trailing /) in the suggestion.
- Retain ALL date and time information from the original note title.

Always follow the below rules, if any, given by the user:
${aiSettings.promptInstructions.pageRenameRules}`,
 
```

You can give it additional instructions in `SETTINGS` like:

``` yaml
ai:
  promptInstructions:
    pageRenameRules: |
      If there is a date or time at the beginning, ensure a hyphen seperates the timestamp from the actual note title.  For example, try to name quick notes like this: "YYYY-MM-DD HH:MM:SS - A short title about the note"
      If tags include #receipt or otherwise looks like a receipt, move it to "Receipts/YYYY/MM-MMMM/" using the date from the note metadata.

```

I might come back and update that first prompt since it seems pretty verbose, but so far it seems to be working pretty well for me.
