### ISSUE TITLE
Unable to change GPT model

### ISSUE THREAD

**Issue by iamdangry** [justyns/silverbullet-ai#32]
Updating the SETTINGS yaml with an alternate GPT model other than the default of 3.5 doesn't appear to take effect.

Snippet from SETTINGS:
```yaml
ai:
  textModels:
  - name: gpt-4o
    provider: openai
    modelName: gpt-4o
```

Console output says it detects a change but the model doesn't change:
![image](https://github.com/justyns/silverbullet-ai/assets/46516977/40343d70-e4d0-4b12-bb7c-47a0dc29dced)

This is further confirmed by the API Usage Dashboard showing my API calls are to `GPT-3.5-turbo-0125` instead of `gpt-4o`
![image](https://github.com/justyns/silverbullet-ai/assets/46516977/2345353f-0613-40ae-b0a7-9b47cda0bce5)

I can update the image model fine via SETTINGS and the console logs the change correctly.

Of course, if I have done a dumb, please let me know.
