### ISSUE TITLE
Support configuring multiple model providers at a time

### ISSUE THREAD

**Issue by justyns** [justyns/silverbullet-ai#4]
Right now we can only configure a single model in the  SETTINGS page.  We can change that to be an array of models instead, something like this:

``` yaml
ai:
  models:
  - name: ollama
    defaultTextModel: phi-2
    apiType: openai
    baseUrl: http://localhost:11434/v1
    requireAuth: false
  - name: openai
    apiType: openai
    defaultTextModel: gpt-4-0125-preview
``` 

`models` probably isn't the right name since each api could support multiple models (e.g. gpt-3 vs gpt-4).  But part of this is so that I can support template prompts with a frontmatter like this:

```yaml
aiprompt:
  description: "Describe the space script functionality you want and generate it"
  system: "You are an expert javascript developer.  Help the user develop new functionality for their personal note taking tool."
  model: gpt-4
```

Each templated prompt would be override the model it uses.  Something like creating a new space script in my example above could go to openai/gpt4, but something like summarizing a personal note would go to a locally-hosted llm instead for privacy reasons.
