### ISSUE TITLE
DeepSeek api provider

### ISSUE THREAD

**Issue by inos-github** [justyns/silverbullet-ai#78]
Is there any chance to support the DeepSeek api?

**Comment by justyns** [comment]
Hi @inos-github

It looks like DeepSeek offers an openai-compatible api according to https://api-docs.deepseek.com/

You should be able to use `https://api.deepseek.com/v1` as the api baseUrl.  If you haven't already, can you verify if that works for you?

I  created an account to test with, but it looks like it's not allowed to add money to it yet.  This is the config I was going to try:

```yaml
ai:
  textModels:
  - name: deepseek-platform-r1
    modelName: deepseek-reasoner
    provider: openai
    baseUrl: https://api.deepseek.com/v1
    secretName: DEEPSEEK_API_KEY
```

`DEEPSEEK_API_KEY` also needs to be in the `SECRETS` file with a key from https://platform.deepseek.com/api_keys
