### ISSUE TITLE
UI trippling on safari

### ISSUE THREAD

**Issue by snake302** [justyns/silverbullet-ai#82]
<img width="538" alt="Image" src="https://github.com/user-attachments/assets/b0e6e75b-b3aa-4b70-8cd2-5c6f2dc95834" />

Hey, this is really weird, but after installing Silverbullet-AI on my Silverbullet, the UI is tripling and this is incredibly annoying. I can confirm that I tested the following combinations:
Silverbullet-AI master & Silverbullet 0.10.4,
Silverbullet-AI 0.4.1 & Silverbullet 0.10.4,
Silverbullet-AI 0.4.1 & Silverbullet 0.10.1.

In all combinations on Safari Version 17.5 (19618.2.12.11.6) on macOS 14.5 (23F79), the UI bar is starting to triple. I can confirm this issue is not happening in Chrome. This is extremely annoying. After removing Silverbullet-AI, everything reverts back to normal.

Here is my settings file. I also tried to specify the UI in the YAML, but this does not change the situation at all.
```
#meta

This page contains some configuration overrides for SilverBullet. A list of configs and their documentation [[!silverbullet.md/SETTINGS|can be found here]].

To update the [[!silverbullet.md/Libraries|libraries]] specified below, run {[Libraries: Update]}

```yaml
indexPage: "[[home]]"
libraries:
- import: "[[!silverbullet.md/Library/Core/*]]"
ai:
imageModels:
- name: dall-e-3
  modelName: dall-e-3
  provider: dalle
textModels:
- name: gpt-4o
  provider: openai
  modelName: gpt-4o
chat:
  bakeMessages: true
  searchEmbeddings: true
  userInformation: >
    I'm a software developer who likes taking notes.
  userInstructions: >
    Please give short and concise responses.  When providing code, do so in python unless requested otherwise.
promptInstructions:
  pageRenameRules: >
    Include a random animal name in every note title.
  tagRules: >
    Tag every note with the current year.
```
```
